### ISSUE TITLE
Can't change from default 0 and 1

### ISSUE THREAD

**Issue by RandomInternetPreson** [neuratech-ai/ComfyUI-MultiGPU#1]
Hello, thank you for making this extension.  How do I change the 0 and 1 gpus to something else like 2 and 3?

I get this error when trying to use the default settings:

Starting server

To see the GUI go to: http://127.0.0.1:8188
got prompt
Failed to validate prompt for output 9:
* DualCLIPLoaderMultiGPU 32:
  - Value not in list: device: 'cuda:1' not in ['cuda:0']
* VAELoaderMultiGPU 33:
  - Value not in list: device: 'cuda:1' not in ['cuda:0']
Output will be ignored
invalid prompt: {'type': 'prompt_outputs_failed_validation', 'message': 'Prompt outputs failed validation', 'details': '', 'extra_info': {}}

I'm on Ubuntu

**Comment by AlexanderDzhoganov** [comment]
Hi. Seems like Comfy is seeing only one GPU `cuda:0`. Make sure `CUDA_VISIBLE_DEVICES` is either unset or contains all GPUs you want to use in Comfy. Same applies to the `--cuda-device` parameter when starting Comfy.

**Comment by RandomInternetPreson** [comment]
Thank you for the reply!  I'm new to comfy can you give me an example of how to edit the cli_args.py file? I understand and have tried setting cuda visible devices to my gpus but the issue is in my inability to edit the cli_args.py file.

I can do something like python main.py --cuda-device 2 and it will use GPU 2, but for the life of me I cannot figure out how to add more than one GPU 😔

Thanks!

**Comment by RandomInternetPreson** [comment]
Argh, I was being a dummy.  Your repo works out of the box, I had edited my cli to do a specific GPU I had to change it back to none.  Now it works!! Thank you so much 💗

**Comment by RandomInternetPreson** [comment]
Works I was doing things wrong.

**Comment by NgoChingYee** [comment]
I don't get it. If I want the cuda 2 and cuda 3 to load VAE and Clip respectively, how do I set the boot parameters?
ComfyUI is seeing only one GPU `cuda:0` too.

Here's how I currently set it up:
`python main.py --cuda-device 2 --listen 0.0.0.0 --port 20012 --enable-cors-header "*"
`

![Image](https://github.com/user-attachments/assets/89849170-e8ff-4216-ab72-5692ee03a4b6)
