### ISSUE TITLE
another idea

### ISSUE THREAD

**Issue by wuhaohezi** [neuratech-ai/ComfyUI-MultiGPU#2]
I believe a better approach would be to directly and conveniently connect to cloud GPUs. The GPU computing power and quantity on a local computer are limited, so it would be better to conveniently connect to cloud GPUs through a script or node and all models /nodes/workflows can use the connected cloud service

**Comment by AlexanderDzhoganov** [comment]
Thanks for the suggestion. This extension is only for local GPUs. Please check https://github.com/city96/ComfyUI_NetDist for distributed inference.
